name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sFTP cpanel  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          port: ${{ secrets.SFTP_PORT }}       # si usas otro puerto, ej: 22
          ssh-private-key: ${{ secrets.SFTP_PRIVATE_KEY }}
          local-path: './'
          remote-path: ${{ secrets.SFTP_REMOTE_PATH }}
          sftp-only: true