name: Deploy to cPanel via SFTP

on:
  push:
    branches:
      - main  # Cambia al branch que quieras desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sFTP cpanel  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}   # <-- Usa contraseña aquí
          port: ${{ secrets.SFTP_PORT }}
          local_path: './'             # Carpeta local a subir
          remote_path: ${{ secrets.SFTP_REMOTE_PATH }}
          sftp_only: true              # Sólo protocolo sftp (sin ssh exec)
