name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sFTP cpanel  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP (SSH sin contraseña)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
          local_path: './'
          remote_path: ${{ secrets.SFTP_REMOTE_PATH }}
          sftp_only: true
